// Common passwords, lowercased, rejected by validatePassword (src/lib/password.ts).
//
// Source: SecLists, Passwords/Common-Credentials/xato-net-10-million-passwords-1000.txt
// (the top 1,000 of the xato.net ten-million-password list; formerly
// 10-million-password-list-top-1000.txt), pinned at commit
// c205c36a445bff37f8e58a9ec829105cd4975c58 (2025-05-08):
// https://raw.githubusercontent.com/danielmiessler/SecLists/c205c36a445bff37f8e58a9ec829105cd4975c58/Passwords/Common-Credentials/xato-net-10-million-passwords-1000.txt
// Fetched 2026-10-10. Only entries of 8+ characters are kept (shorter ones
// already fail the length rule), lowercased and de-duplicated: 201 of 1,000.
//
// SecLists is MIT licensed: Copyright (c) 2018 Daniel Miessler. Permission is
// hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the
// Software without restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions: The above copyright notice and this
// permission notice shall be included in all copies or substantial portions of
// the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO
// EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// A .ts module (not a .txt read at runtime) so the list is bundled into every
// server function on Vercel with no file tracing to get wrong.

export const COMMON_PASSWORDS: ReadonlySet<string> = new Set([
  "password",
  "12345678",
  "123456789",
  "baseball",
  "football",
  "qwertyuiop",
  "1234567890",
  "superman",
  "1qaz2wsx",
  "trustno1",
  "jennifer",
  "sunshine",
  "iloveyou",
  "starwars",
  "computer",
  "michelle",
  "11111111",
  "princess",
  "987654321",
  "corvette",
  "1234qwer",
  "88888888",
  "q1w2e3r4t5",
  "internet",
  "samantha",
  "whatever",
  "maverick",
  "steelers",
  "mercedes",
  "123123123",
  "qwer1234",
  "hardcore",
  "q1w2e3r4",
  "midnight",
  "bigdaddy",
  "victoria",
  "1q2w3e4r",
  "cocacola",
  "marlboro",
  "asdfasdf",
  "87654321",
  "12344321",
  "jordan23",
  "jonathan",
  "liverpoo",
  "danielle",
  "abcd1234",
  "scorpion",
  "qazwsxedc",
  "password1",
  "slipknot",
  "qwerty123",
  "startrek",
  "12341234",
  "redskins",
  "butthead",
  "asdfghjkl",
  "qwertyui",
  "liverpool",
  "dolphins",
  "nicholas",
  "elephant",
  "mountain",
  "xxxxxxxx",
  "1q2w3e4r5t",
  "metallic",
  "shithead",
  "benjamin",
  "creative",
  "rush2112",
  "asdfghjk",
  "4815162342",
  "passw0rd",
  "bullshit",
  "1qazxsw2",
  "garfield",
  "01012011",
  "69696969",
  "december",
  "11223344",
  "godzilla",
  "airborne",
  "lifehack",
  "brooklyn",
  "platinum",
  "darkness",
  "blink182",
  "789456123",
  "12qwaszx",
  "snowball",
  "pakistan",
  "redwings",
  "williams",
  "nintendo",
  "guinness",
  "november",
  "minecraft",
  "asdf1234",
  "lasvegas",
  "babygirl",
  "dickhead",
  "12121212",
  "147258369",
  "explorer",
  "snickers",
  "metallica",
  "alexande",
  "paradise",
  "michigan",
  "carolina",
  "lacrosse",
  "christin",
  "kimberly",
  "kristina",
  "0987654321",
  "poohbear",
  "bollocks",
  "qweasdzxc",
  "drowssap",
  "caroline",
  "einstein",
  "spitfire",
  "maryjane",
  "1232323q",
  "champion",
  "svetlana",
  "westside",
  "courtney",
  "12345qwert",
  "patricia",
  "aaaaaaaa",
  "anderson",
  "security",
  "stargate",
  "simpsons",
  "scarface",
  "123456789a",
  "1234554321",
  "cherokee",
  "usuckballz1",
  "veronica",
  "semperfi",
  "scotland",
  "marshall",
  "qwerty12",
  "98765432",
  "softball",
  "passport",
  "franklin",
  "alexander",
  "55555555",
  "zaq12wsx",
  "infinity",
  "kawasaki",
  "77777777",
  "vladimir",
  "freeuser",
  "wildcats",
  "budlight",
  "brittany",
  "00000000",
  "bulldogs",
  "swordfis",
  "patriots",
  "pearljam",
  "colorado",
  "ncc1701d",
  "motorola",
  "logitech",
  "juventus",
  "wolverin",
  "warcraft",
  "hello123",
  "peekaboo",
  "123654789",
  "panthers",
  "elizabet",
  "spiderma",
  "virginia",
  "valentin",
  "predator",
  "mitchell",
  "741852963",
  "1111111111",
  "rolltide",
  "changeme",
  "lovelove",
  "fktrcfylh",
  "loverboy",
  "chevelle",
  "cardinal",
  "michael1",
  "147852369",
  "american",
  "alexandr",
  "electric",
  "wolfpack",
  "spiderman",
  "darkside",
  "123456789q",
  "01011980",
]);
